/**
 * THE PARITY GATE (CONTRACTS 11.15, F2-A12).
 *
 * One algorithm, two languages. `contracts/scope.expected.json` is generated by
 * `analyzer/tools/gen_scope_fixtures.py` from the PYTHON `project()` over the
 * FROZEN `contracts/graph.sample.json`; this runs the TypeScript port over the
 * same golden and deep-compares every case:
 *
 *   the `nodes` id list IN ORDER · the `edges` id list in order · the `issues`
 *   id list in order · every `issue.nodeIds` in order (so the stable rotation is
 *   checked) · every node's `viewRole` · all eight `stage.nodeCount` /
 *   `issueCounts` / `maxSeverity` rows · `stats` · and the WHOLE `view` object.
 *
 * Plus the six error cases: only the code, the term and the sorted candidate
 * list are contractual — the message prose is deliberately free.
 *
 * A Python-side change the port did not follow fails HERE rather than drifting
 * silently into two products that disagree about what a scope means.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { existsSync } from 'node:fs';
import { loadBundle, readSample, REPO_ROOT } from './helpers.mjs';

const CASES_PATH = join(REPO_ROOT, 'contracts', 'scope.cases.json');
const EXPECTED_PATH = join(REPO_ROOT, 'contracts', 'scope.expected.json');
const HAVE_FIXTURES = existsSync(CASES_PATH) && existsSync(EXPECTED_PATH);

const skip = HAVE_FIXTURES
  ? false
  : 'contracts/scope.cases.json + scope.expected.json are not present — run analyzer/tools/gen_scope_fixtures.py';

const sample = await readSample();
const cases = HAVE_FIXTURES ? JSON.parse(await readFile(CASES_PATH, 'utf8')) : { cases: [] };
const expected = HAVE_FIXTURES ? JSON.parse(await readFile(EXPECTED_PATH, 'utf8')) : { cases: [] };
const { scope: api } = (await loadBundle()).MLView.__internal;

function expectedFor(name) {
  const row = expected.cases.filter((c) => c.name === name)[0];
  assert.ok(row, 'contracts/scope.expected.json has a case named ' + name);
  return row;
}

function plain(value) {
  // Objects built inside the jsdom realm have a different Object.prototype, and
  // assert/strict compares prototypes. Round-trip through JSON, as every other
  // suite here does, so the comparison is about VALUES.
  return JSON.parse(JSON.stringify(value));
}

function ids(list) {
  return list.map((x) => x.id);
}

test('the battery and its expectations describe the same cases', { skip }, () => {
  assert.deepEqual(
    cases.cases.map((c) => c.name),
    expected.cases.map((c) => c.name),
    'scope.cases.json and scope.expected.json list the same case names in the same order',
  );
  assert.equal(cases.graph, 'contracts/graph.sample.json', 'the battery is computed over the FROZEN golden');
});

for (const testCase of cases.cases || []) {
  if (testCase.kind !== 'project') continue;

  test('parity: ' + testCase.name + ' (' + testCase.spec + ')', { skip }, () => {
    const want = expectedFor(testCase.name);
    const scope = api.parseScope(testCase.spec, testCase.depth === null ? undefined : testCase.depth);
    const got = plain(api.project(sample, scope));
    const doc = want.doc;

    assert.deepEqual(ids(got.nodes), ids(doc.nodes), 'node id list, in order');
    assert.deepEqual(ids(got.edges), ids(doc.edges), 'edge id list, in order');
    assert.deepEqual(ids(got.issues), ids(doc.issues), 'issue id list, in order');

    // The stable rotation of step 6 lives or dies here.
    for (let i = 0; i < doc.issues.length; i++) {
      assert.deepEqual(got.issues[i].nodeIds, doc.issues[i].nodeIds, doc.issues[i].id + '.nodeIds, in order');
      assert.deepEqual(got.issues[i].edgeIds, doc.issues[i].edgeIds, doc.issues[i].id + '.edgeIds, in order');
    }

    for (let i = 0; i < doc.nodes.length; i++) {
      assert.equal(got.nodes[i].viewRole, doc.nodes[i].viewRole, doc.nodes[i].id + '.viewRole');
      assert.deepEqual(got.nodes[i].issueIds, doc.nodes[i].issueIds, doc.nodes[i].id + '.issueIds');
    }
    for (let i = 0; i < doc.edges.length; i++) {
      assert.deepEqual(got.edges[i].issueIds, doc.edges[i].issueIds, doc.edges[i].id + '.issueIds');
    }

    assert.equal(got.stages.length, 8, 'all eight stage rows survive a projection');
    for (let i = 0; i < doc.stages.length; i++) {
      const a = got.stages[i];
      const b = doc.stages[i];
      assert.equal(a.id, b.id, 'stage row ' + i + ' id');
      assert.equal(a.nodeCount, b.nodeCount, b.id + '.nodeCount');
      assert.deepEqual(a.issueCounts, b.issueCounts, b.id + '.issueCounts');
      assert.equal(a.maxSeverity, b.maxSeverity, b.id + '.maxSeverity');
      // `present` is PROJECT-LEVEL truth and is carried through verbatim.
      assert.equal(a.present, b.present, b.id + '.present');
      assert.equal(a.order, b.order, b.id + '.order');
    }

    assert.deepEqual(got.stats, doc.stats, 'stats');
    assert.deepEqual(got.view === undefined ? null : got.view, doc.view === undefined ? null : doc.view, 'the whole view object');

    // A projection never restates project-level truth.
    assert.deepEqual(got.workspace, sample.workspace, 'workspace is carried verbatim');
    assert.deepEqual(got.generator, sample.generator, 'generator is carried verbatim');
    assert.equal(got.schemaVersion, sample.schemaVersion);
  });
}

test('every projected array is a SUBSEQUENCE of the unscoped one (F2-A4)', { skip }, () => {
  for (const testCase of cases.cases || []) {
    if (testCase.kind !== 'project') continue;
    const scope = api.parseScope(testCase.spec, testCase.depth === null ? undefined : testCase.depth);
    const got = api.project(sample, scope);
    for (const key of ['nodes', 'edges', 'issues']) {
      assert.ok(isSubsequence(ids(got[key]), ids(sample[key])), testCase.name + ': ' + key + ' is a subsequence, same relative order');
    }
  }
});

for (const testCase of (cases.cases || []).filter((c) => c.kind === 'error')) {
  test('parity error: ' + testCase.name + ' (' + testCase.spec + ')', { skip }, () => {
    const want = expectedFor(testCase.name);
    let thrown = null;
    try {
      const scope = api.parseScope(testCase.spec, testCase.depth === null ? undefined : testCase.depth);
      api.project(sample, scope);
    } catch (err) {
      thrown = err;
    }
    assert.ok(thrown, testCase.spec + ' must be rejected');
    assert.equal(thrown.code, want.error.code, 'error code');
    assert.equal(thrown.term, want.error.term, 'offending term');
    assert.deepEqual(plain(thrown.candidates), want.error.candidates, 'sorted candidate list');
  });
}

test('an unscoped projection carries no view and no viewRole (F2-A13)', { skip: HAVE_FIXTURES ? false : skip }, () => {
  const got = plain(api.project(sample, api.parseScope('all')));
  assert.equal(got.view, undefined, "`all` is not a projection: it must not emit `view`");
  assert.ok(!got.nodes.some((n) => n.viewRole !== undefined), 'no node carries viewRole');
  assert.deepEqual(ids(got.nodes), ids(sample.nodes));
  assert.deepEqual(ids(got.edges), ids(sample.edges));
  assert.deepEqual(ids(got.issues), ids(sample.issues));
});

test('project() is pure: the input document is never mutated', () => {
  const before = JSON.stringify(sample);
  api.project(sample, api.parseScope('unit:train.train', 1));
  api.project(sample, api.parseScope('concern:evaluation'));
  assert.equal(JSON.stringify(sample), before, 'the golden was mutated by a projection');
});

test('two projections of the same document are byte-identical (F2-A9)', () => {
  for (const spec of ['stage:train', 'unit:batch_loop', 'concern:optimization', 'node:n:8d3e0f7a2b61']) {
    const a = JSON.stringify(api.project(sample, api.parseScope(spec)));
    const b = JSON.stringify(api.project(sample, api.parseScope(spec)));
    assert.equal(a, b, spec + ' is deterministic');
  }
});

test('an alias and its canonical concern produce identical documents', () => {
  const alias = JSON.stringify(api.project(sample, api.parseScope('concern:inference')));
  const canonical = JSON.stringify(api.project(sample, api.parseScope('concern:evaluation')));
  assert.equal(alias, canonical, 'concern:inference normalizes to concern:evaluation before validation');
  assert.equal(api.parseScope('symbol:train.train').kind, 'unit', 'symbol: normalizes to unit:');
  assert.equal(api.parseScope('unit:train.train').spec, api.parseScope('SYMBOL:train.train').spec);
});

test('parse -> format -> parse round-trips', () => {
  for (const spec of ['unit:train.train', 'stage:train', 'file:data.py', 'concern:evaluation', 'node:n:8d3e0f7a2b61', 'all']) {
    const once = plain(api.parseScope(spec));
    const twice = plain(api.parseScope(api.formatScope(once), once.depth));
    assert.deepEqual(twice, once, spec + ' round-trips');
  }
});

test('depth is monotone: d0 nodes are a subset of d1, and d1 of d2 (F2-A15)', () => {
  const at = (d) => new Set(api.project(sample, api.parseScope('unit:batch_loop', d)).nodes.map((n) => n.id));
  const d0 = at(0);
  const d1 = at(1);
  const d2 = at(2);
  for (const id of d0) assert.ok(d1.has(id), id + ' survives d0 -> d1');
  for (const id of d1) assert.ok(d2.has(id), id + ' survives d1 -> d2');
  const roles = api.project(sample, api.parseScope('unit:batch_loop', 0)).nodes.map((n) => n.viewRole);
  assert.equal(roles.indexOf('boundary'), -1, 'depth 0 has no boundary-role nodes');
});

function isSubsequence(small, big) {
  let at = 0;
  for (const id of small) {
    const found = big.indexOf(id, at);
    if (found < 0) return false;
    at = found + 1;
  }
  return true;
}
