"""MLV-P11 — render the sample gallery into `docs/gallery/`, on demand.

    PYTHONUTF8=1 python analyzer/tools/gen_gallery.py [--out DIR] [--only MLV101]
                                                      [--clean-only] [--rules-only]
                                                      [--dry-run] [--quiet]

The assets already exist and are invisible. `analyzer/tests/fixtures/rules/` holds
the bad/good pairs that are the **tightest possible illustration of each defect and
its nearest false-positive trap**, sitting in a test directory nobody opens, and
`analyzer/tests/clean/` holds idiomatic correct programs across six framework
shapes — where `samples/README.md` ships two projects, both CIFAR-shaped torch +
sklearn, so a Lightning or HF user has no reference for what good looks like in
their framework.

This is **zero new content**: every page is one of those files, analyzed and
rendered through exactly the pipeline a user's own code goes through, plus an index
that says what each pair is for.

Nothing is committed. ~90 self-contained reports at ~270 KB each is ~25 MB of
generated bytes, so `docs/gallery/` is in `.gitignore` and this script is how you
get it. Run it before a release, before a demo, or when the rule catalogue moves.

**What the index has to be honest about**, because the roadmap makes that a standing
criterion for every part of this product:

* Each page is a **single-file analysis**. The cross-file rules (MLV301, MLV302,
  MLV401, MLV501) structurally cannot fire on one file, and the analyzer says so in
  its own `single_file_analysis` diagnostic. The index repeats it rather than
  letting a reader mistake a short list for a clean bill of health.
* A `_bad.py` fixture that produces **no finding at all** is a real signal about the
  rule, not a rendering failure, so the index marks it rather than hiding it.
* A `_good.py` fixture that produces a finding of the rule it is the negative
  control for is marked too: that is a false positive, and one high-severity false
  positive costs more trust than ten misses.
"""

from __future__ import annotations

import argparse
import html
import os
import sys
import time
from typing import Dict, List, Optional, Sequence, Tuple

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(REPO, "analyzer", "src")
if SRC not in sys.path:
    sys.path.insert(0, SRC)

from mlview.api import AnalyzeOptions, analyze_to_dict, render_html  # noqa: E402
from mlview.rules.registry import RuleSpec, all_rules, discover_rules  # noqa: E402

FIXTURES = os.path.join(REPO, "analyzer", "tests", "fixtures", "rules")
CLEAN = os.path.join(REPO, "analyzer", "tests", "clean")
DEFAULT_OUT = os.path.join(REPO, "docs", "gallery")

#: What each clean program is a reference for. A framework name is the thing a
#: reader is actually looking for ("what does good look like in Lightning?").
CLEAN_NOTES: Dict[str, str] = {
    "vanilla_torch.py": "A hand-written PyTorch training loop: split, seed, "
                        "zero_grad/backward/step in order, eval() before validation.",
    "lightning_module.py": "The same pipeline as a Lightning module, where the loop "
                           "is the framework's and MLView must not ask for it twice.",
    "hf_trainer.py": "Hugging Face `Trainer`: the loop, the optimizer and the "
                     "evaluation are all inside the framework.",
    "sklearn_pipeline.py": "The scikit-learn answer to leakage: a `Pipeline` fitted "
                           "inside cross-validation, so no transformer ever sees the test fold.",
    "amp_accumulation.py": "Mixed precision plus gradient accumulation - the shape "
                           "that makes a naive train-loop rule fire on correct code.",
    "timeseries_split.py": "`TimeSeriesSplit`: a chronological split, which a rule "
                           "that assumes `train_test_split` would call a missing holdout.",
}


class Page:
    """One rendered report and the facts the index states about it."""

    def __init__(self, title: str, source: str, relative: str) -> None:
        self.title = title
        self.source = source
        self.relative = relative
        self.counts = {"high": 0, "medium": 0, "low": 0}
        self.codes: List[str] = []
        self.nodes = 0
        self.diagnostics: List[str] = []
        self.error: Optional[str] = None

    @property
    def total(self) -> int:
        return sum(self.counts.values())


def _relative(path: str) -> str:
    return os.path.relpath(path, REPO).replace("\\", "/")


def analyze_one(source: str, out_file: str, dry_run: bool) -> Page:
    """Analyze one file and write its report. A failure is recorded, never raised."""
    page = Page(os.path.basename(source), _relative(source), _relative(out_file))
    try:
        graph = analyze_to_dict(AnalyzeOptions(paths=(source,)))
    except Exception as exc:  # a broken fixture must not sink the whole gallery
        page.error = "%s: %s" % (type(exc).__name__, exc)
        return page
    for issue in graph.get("issues", []):
        if issue.get("suppressed"):
            continue
        severity = str(issue.get("severity", "low"))
        if severity in page.counts:
            page.counts[severity] += 1
        code = str(issue.get("code", ""))
        if code and code not in page.codes:
            page.codes.append(code)
    page.codes.sort()
    page.nodes = int(graph.get("stats", {}).get("nodes", 0) or 0)
    for diagnostic in graph.get("diagnostics", []):
        kind = str(diagnostic.get("kind", ""))
        if kind and kind not in page.diagnostics:
            page.diagnostics.append(kind)
    if not dry_run:
        os.makedirs(os.path.dirname(out_file), exist_ok=True)
        try:
            render_html(graph, out_file)
        except Exception as exc:
            page.error = "render failed: %s" % exc
    return page


def rule_pairs(only: Optional[str]) -> List[Tuple[RuleSpec, List[str]]]:
    """Every registered rule with the fixture files that illustrate it."""
    discover_rules()
    if not os.path.isdir(FIXTURES):
        return []
    present = sorted(f for f in os.listdir(FIXTURES) if f.endswith(".py"))
    pairs: List[Tuple[RuleSpec, List[str]]] = []
    for spec in sorted(all_rules(), key=lambda s: s.code):
        if only and spec.code.upper() != only.upper():
            continue
        files = [f for f in present if f.startswith(spec.code + "_")]
        if files:
            pairs.append((spec, files))
    return pairs


def clean_programs() -> List[str]:
    if not os.path.isdir(CLEAN):
        return []
    return sorted(
        os.path.join(CLEAN, name)
        for name in os.listdir(CLEAN)
        if name.endswith(".py") and not name.startswith("_")
    )


# ------------------------------------------------------------------------- the index
def _esc(text: object) -> str:
    return html.escape(str(text), quote=True)


def _counts_cell(page: Page) -> str:
    if page.error:
        return '<span class="err">error</span>'
    if page.total == 0:
        return '<span class="zero">0</span>'
    parts = [
        '<span class="sev-%s">%d %s</span>' % (name, page.counts[name], name)
        for name in ("high", "medium", "low")
        if page.counts[name]
    ]
    return " · ".join(parts)


def _row(page: Page, note: str, flags: Sequence[str]) -> str:
    marks = "".join('<span class="flag">%s</span>' % _esc(f) for f in flags)
    codes = ", ".join(page.codes) if page.codes else "—"
    return (
        "<tr>"
        '<td><a href="%s">%s</a>%s</td>'
        '<td class="counts">%s</td>'
        "<td><code>%s</code></td>"
        '<td class="note">%s</td>'
        "</tr>"
        % (
            _esc(os.path.relpath(page.relative, "docs/gallery").replace("\\", "/")),
            _esc(page.title),
            marks,
            _counts_cell(page),
            _esc(codes),
            _esc(note),
        )
    )


STYLE = """
:root { color-scheme: light dark; --fg:#12151c; --bg:#fbfbfd; --muted:#5c6473;
        --rule:#d9dde6; --card:#ffffff; --high:#b3261e; --medium:#8a5a00; --low:#3a5a9b; }
@media (prefers-color-scheme: dark) {
  :root { --fg:#e7eaf0; --bg:#0e1420; --muted:#98a2b3; --rule:#243044; --card:#141c2b;
          --high:#ff8a80; --medium:#f0b429; --low:#8ab4f8; }
}
* { box-sizing: border-box; }
body { margin:0; padding:2.5rem 1.25rem 4rem; background:var(--bg); color:var(--fg);
       font:15px/1.55 ui-sans-serif,-apple-system,Segoe UI,Roboto,sans-serif; }
main { max-width: 62rem; margin: 0 auto; }
h1 { font-size:1.6rem; margin:0 0 .25rem; letter-spacing:-.01em; }
h2 { font-size:1.1rem; margin:2.5rem 0 .5rem; }
p.lede { color:var(--muted); margin:.25rem 0 1.5rem; max-width:46rem; }
.caveat { border-left:3px solid var(--medium); background:var(--card); padding:.75rem 1rem;
          margin:1rem 0 1.5rem; border-radius:0 6px 6px 0; }
.caveat p { margin:.35rem 0; }
table { width:100%; border-collapse:collapse; margin:.5rem 0 1rem; }
th, td { text-align:left; padding:.5rem .6rem; border-bottom:1px solid var(--rule);
         vertical-align:top; }
th { font-size:.78rem; text-transform:uppercase; letter-spacing:.05em; color:var(--muted); }
td.counts { white-space:nowrap; }
td.note { color:var(--muted); font-size:.9rem; }
a { color:inherit; }
code { font:13px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace; color:var(--muted); }
.sev-high { color:var(--high); font-weight:600; }
.sev-medium { color:var(--medium); font-weight:600; }
.sev-low { color:var(--low); }
.zero { color:var(--muted); }
.err { color:var(--high); font-weight:600; }
.flag { display:inline-block; margin-left:.4rem; padding:.05rem .4rem; border-radius:999px;
        font-size:.72rem; background:var(--medium); color:#000; }
footer { color:var(--muted); font-size:.85rem; margin-top:3rem;
         border-top:1px solid var(--rule); padding-top:1rem; }
"""


def _all_pages(
    rules: List[Tuple[RuleSpec, List[Tuple[Page, str, List[str]]]]],
    cleans: List[Page],
) -> List[Page]:
    return list(cleans) + [page for _spec, rendered in rules for page, _n, _f in rendered]


def blindspot_caveat(pages: List[Page]) -> str:
    """The gallery's own blind spot, **measured on this run**.

    GALLERY-FALSE-BLINDSPOT: this paragraph used to be a constant asserting
    that MLV301 / MLV302 / MLV401 / MLV501 "structurally cannot fire here" and
    that "the analyzer says so on every page as a `single_file_analysis`
    diagnostic". Both halves were false on this build. All four fire on their
    own self-contained fixtures - the tables two sections below say so - and
    `core/coverage.single_file_diagnostic` only speaks when an analyzed module
    *imports* a sibling that was left out, which no rule fixture does, so 0 of
    90 pages carried one.

    Telling a reader the tool was blind where it was not is the same failure as
    telling them it looked where it did not; the standing criterion cuts both
    ways. So the numbers come off the run.
    """
    with_note = [p for p in pages if "single_file_analysis" in p.diagnostics]
    cross = [spec.code for spec in all_rules() if spec.enabled and spec.cross_file]
    fired = sorted({c for p in pages for c in p.codes if c in cross})
    quiet = [c for c in sorted(cross) if c not in fired]
    said = (
        "<p><strong>Each page is a single-file analysis.</strong> Any finding that "
        "would have needed a sibling module is missing from it, and nothing on the "
        "page can tell you which: a short list here is not a clean bill of health.</p>"
    )
    said += (
        "<p>%d of %d page(s) carry a <code>single_file_analysis</code> diagnostic. "
        "That diagnostic fires only when an analyzed module <em>imports</em> a sibling "
        "the run left out, so a self-contained fixture gets none — the silence is the "
        "analyzer being accurate about this corpus, not about your project.</p>"
        % (len(with_note), len(pages))
    )
    if cross:
        said += (
            "<p>The rules whose evidence usually lives in another module are %s. "
            "On this run %s fired on at least one single-file page%s.</p>"
            % (
                ", ".join("<code>%s</code>" % _esc(c) for c in sorted(cross)),
                (", ".join("<code>%s</code>" % _esc(c) for c in fired) or "none of them"),
                (" and %s did not"
                 % ", ".join("<code>%s</code>" % _esc(c) for c in quiet)) if quiet else "",
            )
        )
    return said


def write_index(
    out_dir: str,
    rules: List[Tuple[RuleSpec, List[Tuple[Page, str, List[str]]]]],
    cleans: List[Page],
    seconds: float,
) -> str:
    parts: List[str] = [
        "<!doctype html>",
        '<html lang="en"><head><meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width,initial-scale=1">',
        "<title>MLView gallery</title>",
        "<style>%s</style></head><body><main>" % STYLE,
        "<h1>MLView gallery</h1>",
        '<p class="lede">Every rule fixture and every clean reference program, analyzed and '
        "rendered through the same pipeline your own code goes through. Generated by "
        "<code>analyzer/tools/gen_gallery.py</code>; nothing here is committed.</p>",
        '<div class="caveat">',
        blindspot_caveat(_all_pages(rules, cleans)),
        "<p>A <code>_bad.py</code> that reports <strong>0</strong>, or a "
        "<code>_good.py</code> that reports its own rule, is marked below. Both are facts "
        "about the rule rather than about the page.</p>",
        "</div>",
        "<h2>What good looks like</h2>",
        '<p class="lede">Idiomatic, correct programs across six framework shapes. These are '
        "the reference the two bundled samples cannot be, because both of those are "
        "CIFAR-shaped torch + sklearn.</p>",
        "<table><thead><tr><th>Program</th><th>Findings</th><th>Codes</th>"
        "<th>What it demonstrates</th></tr></thead><tbody>",
    ]
    for page in cleans:
        flags = [] if page.total == 0 else ["finding on clean code"]
        parts.append(_row(page, CLEAN_NOTES.get(page.title, ""), flags))
    parts.append("</tbody></table>")

    parts.append("<h2>Rule fixtures</h2>")
    parts.append(
        '<p class="lede">For each rule, the smallest program that triggers it and the '
        "nearest program that must <em>not</em> — the false-positive trap the rule was "
        "written against.</p>"
    )
    for spec, pages in rules:
        parts.append(
            "<h3>%s — %s <code>(%s)</code></h3>"
            % (_esc(spec.code), _esc(spec.title), _esc(spec.severity))
        )
        parts.append(
            "<table><thead><tr><th>Fixture</th><th>Findings</th><th>Codes</th>"
            "<th>Note</th></tr></thead><tbody>"
        )
        for page, note, flags in pages:
            parts.append(_row(page, note, flags))
        parts.append("</tbody></table>")

    total = len(cleans) + sum(len(p) for _s, p in rules)
    parts.append(
        "<footer>%d page(s) rendered in %.1f s from %d rule(s) and %d clean program(s). "
        "Regenerate with <code>python analyzer/tools/gen_gallery.py</code>.</footer>"
        % (total, seconds, len(rules), len(cleans))
    )
    parts.append("</main></body></html>")

    os.makedirs(out_dir, exist_ok=True)
    index = os.path.join(out_dir, "index.html")
    with open(index, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(parts))
        fh.write("\n")
    return index


# -------------------------------------------------------------------------- the driver
def _fixture_note(name: str, code: str) -> Tuple[str, List[str]]:
    stem = name[:-3]
    tail = stem[len(code) + 1:] if stem.startswith(code + "_") else stem
    if tail == "bad":
        return "The defect, as small as it gets.", []
    if tail == "good":
        return "The nearest correct program: this must stay silent.", []
    variant = tail.replace("_", " ")
    if variant.endswith(" good"):
        return "A correct variant (%s) the rule must not fire on." % variant[:-5], []
    return "A further variant of the defect (%s)." % variant.replace(" bad", ""), []


def build(out_dir: str, only: Optional[str], what: str, dry_run: bool, quiet: bool) -> int:
    started = time.time()
    say = (lambda *a: None) if quiet else (lambda *a: print(*a, file=sys.stderr))

    cleans: List[Page] = []
    if what in ("all", "clean"):
        for source in clean_programs():
            name = os.path.basename(source)
            page = analyze_one(source, os.path.join(out_dir, "clean", name[:-3] + ".html"), dry_run)
            cleans.append(page)
            say("clean  %-24s %d node(s), %d finding(s)" % (name, page.nodes, page.total))

    rules: List[Tuple[RuleSpec, List[Tuple[Page, str, List[str]]]]] = []
    if what in ("all", "rules"):
        for spec, files in rule_pairs(only):
            rendered: List[Tuple[Page, str, List[str]]] = []
            for name in files:
                out_file = os.path.join(out_dir, "rules", spec.code, name[:-3] + ".html")
                page = analyze_one(os.path.join(FIXTURES, name), out_file, dry_run)
                note, flags = _fixture_note(name, spec.code)
                # The two facts the index must not hide.
                if name.endswith("_bad.py") and spec.code not in page.codes:
                    flags = list(flags) + ["%s did not fire" % spec.code]
                if "good" in name and spec.code in page.codes:
                    flags = list(flags) + ["FALSE POSITIVE"]
                rendered.append((page, note, flags))
                say("rule   %-24s %d finding(s) %s" % (name, page.total, ",".join(page.codes)))
            rules.append((spec, rendered))

    seconds = time.time() - started
    if dry_run:
        say("dry run: %d page(s) would be written under %s"
            % (len(cleans) + sum(len(p) for _s, p in rules), out_dir))
        return 0
    index = write_index(out_dir, rules, cleans, seconds)
    # The ONE stdout line, because this is a generator a human runs: the path to open.
    print(index)
    return 0


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="gen_gallery",
        description="Render every rule fixture and clean program into docs/gallery/.",
    )
    parser.add_argument("--out", default=DEFAULT_OUT, metavar="DIR",
                        help="where to write (default: docs/gallery, which is gitignored)")
    parser.add_argument("--only", metavar="MLV101", help="one rule code")
    parser.add_argument("--clean-only", action="store_true", help="only the clean programs")
    parser.add_argument("--rules-only", action="store_true", help="only the rule fixtures")
    parser.add_argument("--dry-run", action="store_true",
                        help="analyze everything and report, writing nothing")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(list(argv) if argv is not None else None)
    what = "clean" if args.clean_only else "rules" if args.rules_only else "all"
    return build(os.path.abspath(args.out), args.only, what, args.dry_run, args.quiet)


if __name__ == "__main__":
    raise SystemExit(main())
