"""Regenerate the scope parity fixtures from the Python `project()`.

    PYTHONUTF8=1 python analyzer/tools/gen_scope_fixtures.py [--check]

Writes two files, both computed over the **frozen** `contracts/graph.sample.json`
so the gate can never churn when a rule changes (CONTRACTS 11.15, FEATURES 7):

* ``contracts/scope.cases.json``    - the inputs: ten projecting cases plus one
  case per error code. Hand-readable, and the only file a port needs to iterate.
* ``contracts/scope.expected.json`` - the outputs: the full projected document
  for every projecting case, and ``{code, term, candidates}`` for every error
  case.

``--check`` regenerates in memory and byte-diffs against the files on disk,
exiting 1 on drift; it writes nothing. `tools/verify.py --scopes` runs it.

Consumers deep-compare: the `nodes` / `edges` / `issues` id lists **in order**,
every `issue.nodeIds` (so the stable rotation is checked), every node's
`viewRole`, all eight `stage.nodeCount` / `issueCounts` / `maxSeverity`,
`stats`, and the whole `view` object. `diagnostics` prose is deliberately NOT
contractual - only the codes, terms and candidate lists of errors are.
"""

from __future__ import annotations

import argparse
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(REPO, "analyzer", "src")
if SRC not in sys.path:
    sys.path.insert(0, SRC)

from mlview.core.project import ScopeError, parse_scope, project  # noqa: E402

GRAPH = os.path.join(REPO, "contracts", "graph.sample.json")
CASES = os.path.join(REPO, "contracts", "scope.cases.json")
EXPECTED = os.path.join(REPO, "contracts", "scope.expected.json")
GRAPH_REL = "contracts/graph.sample.json"
GENERATOR = "analyzer/tools/gen_scope_fixtures.py"

#: (name, spec, depth, note). `depth: None` means "the per-kind default".
PROJECTING = [
    ("all", "all", None,
     "identity: the output equals the input and carries no `view`"),
    ("stage_train", "stage:train", 0, "a whole lane, no boundary ring"),
    ("unit_train_train", "unit:train.train", 1,
     "tier-1 qualname hit, descendant closure, one boundary ring"),
    ("unit_batch_loop_d0", "unit:batch_loop", 0,
     "tier-3 bare name; exercises the ancestor closure (context)"),
    ("unit_batch_loop_d2", "unit:batch_loop", 2, "depth monotonicity against d0"),
    ("file_data_py", "file:data.py", 0, "bare basename match"),
    ("concern_evaluation", "concern:evaluation", 0, "a preset over eval + deliver"),
    ("concern_optimization", "concern:optimization", 0,
     "a preset over model + objective + train"),
    ("node_smallnet", "node:n:8d3e0f7a2b61", 1,
     "legacy pinpoint selector; exercises the stable rotation of issue.nodeIds"),
    ("unit_nope", "unit:Nope", None,
     "empty but legal: eight stage rows at nodeCount 0, view.empty true, exit 0"),
]

#: One case per error code (`unknown_unit` is never raised - see 11.2 step 9).
ERRORS = [
    ("err_bad_selector", "bogus:x", None, "unknown kind"),
    ("err_unknown_stage", "stage:nope", None, "not one of the eight StageIds"),
    ("err_unknown_concern", "concern:nope", None, "not a preset or an alias"),
    ("err_unknown_node", "node:n:deadbeefdead", None, "no such node in this graph"),
    ("err_unknown_file", "file:nope.py", None, "no loc.file matches"),
    ("err_bad_depth", "stage:train", 3, "depth outside 0..2"),
]


def load_graph(path: str = GRAPH):
    with io.open(path, encoding="utf-8-sig") as fh:
        return json.load(fh)


def build_cases():
    """The inputs, exactly as both ports iterate them."""
    cases = [{"name": name, "kind": "project", "spec": spec, "depth": depth,
              "note": note} for name, spec, depth, note in PROJECTING]
    cases += [{"name": name, "kind": "error", "spec": spec, "depth": depth,
               "note": note} for name, spec, depth, note in ERRORS]
    return {
        "$comment": "Scope parity battery (CONTRACTS 11.15). Inputs only; the "
                    "expected outputs live in contracts/scope.expected.json. "
                    "Both are generated by " + GENERATOR + " - do not hand-edit.",
        "version": 1,
        "graph": GRAPH_REL,
        "generatedBy": GENERATOR,
        "cases": cases,
    }


def build_expected(graph):
    """The outputs: a full projected document, or an error triple."""
    out = []
    for name, spec, depth, _note in PROJECTING:
        doc = project(graph, parse_scope(spec, depth))
        out.append({"name": name, "kind": "project", "spec": spec, "depth": depth,
                    "doc": doc})
    for name, spec, depth, _note in ERRORS:
        raised_by = "parse"
        try:
            scope = parse_scope(spec, depth)
        except ScopeError as exc:
            error = exc
        else:
            raised_by = "resolve"
            try:
                project(graph, scope)
            except ScopeError as exc:
                error = exc
            else:
                raise SystemExit("case %s did not raise" % name)
        out.append({"name": name, "kind": "error", "spec": spec, "depth": depth,
                    "raisedBy": raised_by,
                    "error": {"code": error.code, "term": error.term,
                              "candidates": list(error.candidates)}})
    return {
        "$comment": "Expected output of project() for every case in "
                    "contracts/scope.cases.json, generated from the Python "
                    "implementation by " + GENERATOR + ". `diagnostics` prose is "
                    "NOT contractual; ids, order, roles, aggregates, `view` and "
                    "the error triples are.",
        "version": 1,
        "graph": GRAPH_REL,
        "generatedBy": GENERATOR,
        "cases": out,
    }


def render(payload) -> str:
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _read(path: str) -> str:
    if not os.path.exists(path):
        return ""
    with io.open(path, encoding="utf-8") as fh:
        return fh.read()


def _write(path: str, text: str) -> None:
    with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if either file on disk is out of date")
    args = parser.parse_args(argv)

    graph = load_graph()
    files = [(CASES, render(build_cases())), (EXPECTED, render(build_expected(graph)))]
    summary = ("%d projecting case(s) + %d error case(s) over %s"
               % (len(PROJECTING), len(ERRORS), GRAPH_REL))

    if args.check:
        stale = [path for path, text in files if _read(path) != text]
        if stale:
            sys.stderr.write("scope fixtures are out of date: %s\n"
                             % ", ".join(os.path.basename(p) for p in stale))
            return 1
        sys.stderr.write("scope fixtures are current: %s\n" % summary)
        return 0

    for path, text in files:
        _write(path, text)
        sys.stderr.write("wrote %s (%d bytes)\n"
                         % (path.replace("\\", "/"), len(text.encode("utf-8"))))
    sys.stderr.write("%s\n" % summary)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
